development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "6b66a88d34ab4594ba8f6c102b3dc83a9e5f15ee311d12fb8c5aa463e8d1f83f"
  signature_expiration: 3600 # one hour
