app:
  name: My Community
sysop:
  email: sysop@example.com
oauth:
  facebook:
    app_id: APP_ID
    app_secret: APP_SECRET
  twitter:
    consumer_key: CONSUMER_KEY
    consumer_secret: CONSUMER_SECRET
locale: en