app:
  name: 'My Community'
domain: 'mycommunity.example.com'
sysop:
  email: 'sysop@example.com'
locale: 'en'
recaptcha:
  enabled: true
  public_key: 'PUBLIC_KEY'
  private_key: 'PRIVATE_KEY'
  proxy: 'http://proxy.example.com'
  theme: 'white'
authentication:
  encryptor: 'bcrypt'
  pepper: 'samplexpepper'
google_analytics:
  account_id: ''
facebook:
  page: 'platform'
  app_id: 'APP_ID'
  app_secret: 'APP_SECRET'
twitter:
  username: 'my_twitter_user'
  widget_id: 'WIDGET_ID'
  consumer_key: 'CONSUMER_KEY'
  consumer_secret: 'CONSUMER_SECRET'