app:
  name: 'My Community'
sysop:
  email: 'sysop@example.com'
oauth:
  facebook:
    app_id: 'APP_ID'
    app_secret: 'APP_SECRET'
  twitter:
    consumer_key: 'CONSUMER_KEY'
    consumer_secret: 'CONSUMER_SECRET'
locale: 'pt-BR'
recaptcha:
  enabled: true
  public_key: 'PUBLIC_KEY'
  private_key: 'PRIVATE_KEY'
  proxy: 'http://proxy.example.com'
  theme: 'white'